apiVersion: v1
kind: Service
metadata:
  name: {{ include "sql-statefull-deploy.fullname" . }}
  {{- if .Values.service.annotations }}
  {{- with .Values.service.annotations }}
  annotations:
  {{ toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- end }}
  labels:
    {{- include "sql-statefull-deploy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "sql-statefull-deploy.selectorLabels" . | nindent 4 }}
