apiVersion: v1
kind: Service
metadata:
  name: {{ include "mssql-latest.fullname" . }}
  labels:
    {{- include "mssql-latest.labels" . | nindent 4 }}
  {{- if .Values.service.annotations }}
  {{- with .Values.service.annotations }}
  annotations:
  {{ toYaml . | trim | nindent 4 }}
  {{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    {{- include "mssql-latest.selectorLabels" . | nindent 4 }}
